# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('salary_range', models.CharField(blank=True, choices=[('n', 'A combinar'), ('j', 'Até R$ 2.500'), ('f', 'R$ 2.501 a R$ 3.500'), ('s', 'R$ 3.501 a R$ 6.000'), ('p', 'Acima de R$ 6.000')], max_length=1)),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('skills', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.Category')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.JobType'),
        ),
    ]
