# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('n', 'A combinar'), ('j', 'Ate R$ 2.500'), ('f', 'R$ 2.501 a R$ 3.500'), ('s', 'R$ 3.501 a R$ 6.000'), ('p', 'Acima de R$ 6.000')], max_length=1),
        ),
    ]
