# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0012_auto_20160416_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
