# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0013_job_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='enabled',
            new_name='published',
        ),
    ]
