# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0016_auto_20160425_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.Salary'),
        ),
    ]
