# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0017_auto_20160425_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('n/a', 'A combinar'), ('junior', 'Até R$ 2.500'), ('full', 'R$ 2.501 a R$ 3.500'), ('senior', 'R$ 3.501 a R$ 5.000'), ('specialist', 'Acima de R$ 5.000')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
