# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0019_auto_20160425_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
