# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0019_auto_20160425_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=19),
        ),
    ]
